### ISSUE TITLE
Where should I change the code if I want to use a different image resolution for training, such as 640x640, instead of the default 320x320?

### ISSUE THREAD

**Issue by Quintonkd** [flyinghu123/CPR#14]
when i only modify the train image size config to 640，the error reports：

![image](https://github.com/user-attachments/assets/93368a47-5c43-45fc-84cc-c90cff24b2f9)

and then i replace the line 43 in test.py：
train_local_features = [torch.zeros((len(train_fns), out_channels, *shape[2:]), device='cuda') for shape, out_channels in zip([torch.Size([2,256,160,160]),torch.Size([2,512,80,80])], model.lrb.out_channels_list)]
it seems require a massive gpu memories：
![image](https://github.com/user-attachments/assets/efeaef9e-76e2-4ba9-9690-3fb6e58ba3bc)

**Comment by flyinghu123** [comment]
When you set the  image size to 640, you may need to modify some configurations related to the size. If you hava a "cuda out of memory" error, you can consider reducing the GPU memory usage. Here are a few suggestions:

1. Reduce the output dimension of the last layer: For example, you can reduce the output dimension from 384 to 16.
2. Switch to online feature extraction mode: Instead of pre-extracting the local features of train samples, you can extract the features of the retrieved train samples in real time during the inference. 


These adjustments should help mitigate the memory issues you are experiencing.

**Comment by Quintonkd** [comment]
Thanks for ur reply, i will try it.
